[alembic]
script_location = alembic
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s
prepend_sys_path = .
timezone = UTC

# Использование asyncpg
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/rag_db

[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,sentinel,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sentinel]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S