"""add_run_metadata_to_agent_runs

Revision ID: 17b67966d8bc
Revises: '9983b6f68940'
Create Date: 2026-08-12 23:55:19.674364+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17b67966d8bc'
down_revision: Union[str, None] = '9983b6f68940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('run_metadata', sa.JSON(), nullable=False, comment='Метаданные запуска в формате JSON'))
    op.add_column('agent_runs', sa.Column('error_message', sa.Text(), nullable=True, comment='Текст ошибки при сбое выполнения'))
    op.add_column('agent_runs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления (UTC)'))
    op.alter_column('agent_runs', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор запуска',
               existing_nullable=False)
    op.alter_column('agent_runs', 'user_id',
               existing_type=sa.UUID(),
               comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('agent_runs', 'prompt',
               existing_type=sa.TEXT(),
               comment='Исходный запрос пользователя',
               existing_nullable=False)
    op.alter_column('agent_runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               comment='Текущий статус выполнения задачи',
               existing_nullable=False)
    op.alter_column('agent_runs', 'final_answer',
               existing_type=sa.TEXT(),
               comment='Сгенерированный итоговый ответ агента',
               existing_nullable=True)
    op.alter_column('agent_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания записи (UTC)',
               existing_nullable=False)
    op.alter_column('agent_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время завершения (UTC)',
               existing_nullable=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.alter_column('raw_rl_transitions', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('raw_rl_transitions', 'next_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('raw_rl_transitions', 'next_action_mask',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор сообщения outbox',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'event_id',
               existing_type=sa.UUID(),
               comment='Идентификатор исходного события',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'aggregate_id',
               existing_type=sa.UUID(),
               comment='Идентификатор сущности (например, run_id)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               comment='Тип события (например, RUN_CREATED)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Тело события в формате JSON',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               comment='Статус обработки: PENDING, PROCESSED, FAILED',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'retry_count',
               existing_type=sa.INTEGER(),
               comment='Количество попыток отправки',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'error',
               existing_type=sa.TEXT(),
               comment='Текст последней ошибки при отправке',
               existing_nullable=True)
    op.alter_column('transactional_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время создания события (UTC)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время публикации в брокер (UTC)',
               existing_nullable=True)
    op.drop_constraint(op.f('transactional_outbox_event_id_key'), 'transactional_outbox', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('transactional_outbox_event_id_key'), 'transactional_outbox', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('transactional_outbox', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время публикации в брокер (UTC)',
               existing_nullable=True)
    op.alter_column('transactional_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время создания события (UTC)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст последней ошибки при отправке',
               existing_nullable=True)
    op.alter_column('transactional_outbox', 'retry_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество попыток отправки',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Статус обработки: PENDING, PROCESSED, FAILED',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Тело события в формате JSON',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'event_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Тип события (например, RUN_CREATED)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'aggregate_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Идентификатор сущности (например, run_id)',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Идентификатор исходного события',
               existing_nullable=False)
    op.alter_column('transactional_outbox', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор сообщения outbox',
               existing_nullable=False)
    op.alter_column('raw_rl_transitions', 'next_action_mask',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('raw_rl_transitions', 'next_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('raw_rl_transitions', 'state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.alter_column('agent_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время завершения (UTC)',
               existing_nullable=True)
    op.alter_column('agent_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время создания записи (UTC)',
               existing_nullable=False)
    op.alter_column('agent_runs', 'final_answer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Сгенерированный итоговый ответ агента',
               existing_nullable=True)
    op.alter_column('agent_runs', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Текущий статус выполнения задачи',
               existing_nullable=False)
    op.alter_column('agent_runs', 'prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Исходный запрос пользователя',
               existing_nullable=False)
    op.alter_column('agent_runs', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('agent_runs', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор запуска',
               existing_nullable=False)
    op.drop_column('agent_runs', 'updated_at')
    op.drop_column('agent_runs', 'error_message')
    op.drop_column('agent_runs', 'run_metadata')
    # ### end Alembic commands ###