"""add transactional outbox table

Revision ID: 9983b6f68940
Revises: None
Create Date: 2026-08-12 20:11:35.529062+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9983b6f68940'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('transactional_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('RUN_STARTED', 'STEP_EXECUTED', 'EXECUTION_COMPLETED', 'EXECUTION_FAILED', 'EXECUTION_CANCELLED', 'FEEDBACK_RECEIVED', 'REWARD_CALCULATED', name='eventtype', native_enum=False, length=50), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_transactional_outbox_aggregate_id'), 'transactional_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_transactional_outbox_event_type'), 'transactional_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_transactional_outbox_status'), 'transactional_outbox', ['status'], unique=False)
    op.create_table('raw_rl_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('trajectory_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('hierarchy_level', sa.Enum('HIGH', 'LOW', name='hierarchylevel', native_enum=False, length=10), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_index', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(length=255), nullable=False),
    sa.Column('next_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('next_action_mask', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward_status', sa.Enum('PENDING', 'CALCULATED', 'FAILED', name='rewardstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reward_value', sa.Float(), nullable=True),
    sa.Column('observation_schema_version', sa.String(length=50), nullable=False),
    sa.Column('action_space_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transitions_reward_status', 'raw_rl_transitions', ['reward_status'], unique=False)
    op.create_index('idx_transitions_run_level', 'raw_rl_transitions', ['run_id', 'hierarchy_level'], unique=False)
    op.create_index(op.f('ix_raw_rl_transitions_run_id'), 'raw_rl_transitions', ['run_id'], unique=False)
    op.create_index(op.f('ix_raw_rl_transitions_trajectory_id'), 'raw_rl_transitions', ['trajectory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_rl_transitions_trajectory_id'), table_name='raw_rl_transitions')
    op.drop_index(op.f('ix_raw_rl_transitions_run_id'), table_name='raw_rl_transitions')
    op.drop_index('idx_transitions_run_level', table_name='raw_rl_transitions')
    op.drop_index('idx_transitions_reward_status', table_name='raw_rl_transitions')
    op.drop_table('raw_rl_transitions')
    op.drop_index(op.f('ix_transactional_outbox_status'), table_name='transactional_outbox')
    op.drop_index(op.f('ix_transactional_outbox_event_type'), table_name='transactional_outbox')
    op.drop_index(op.f('ix_transactional_outbox_aggregate_id'), table_name='transactional_outbox')
    op.drop_table('transactional_outbox')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###